In [1]:
import json
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "raw" / "api" / "github" / "repo_response.json"

input_file

PosixPath('/Users/reda.serhir/Documents/Projects/Github/python-data-toolbox/data/raw/api/github/repo_response.json')

In [3]:
with open(input_file, "r") as file:
    repo_data = json.load(file)

type(repo_data), len(repo_data)

(list, 2)

In [4]:
repo_data[0]

{'id': 1191068241,
 'node_id': 'R_kgDORv5CUQ',
 'name': 'python-data-toolbox',
 'full_name': 'redserlabs/python-data-toolbox',
 'private': False,
 'owner': {'login': 'redserlabs',
  'id': 217943364,
  'node_id': 'U_kgDODP2NRA',
  'avatar_url': 'https://avatars.githubusercontent.com/u/217943364?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/redserlabs',
  'html_url': 'https://github.com/redserlabs',
  'followers_url': 'https://api.github.com/users/redserlabs/followers',
  'following_url': 'https://api.github.com/users/redserlabs/following{/other_user}',
  'gists_url': 'https://api.github.com/users/redserlabs/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/redserlabs/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/redserlabs/subscriptions',
  'organizations_url': 'https://api.github.com/users/redserlabs/orgs',
  'repos_url': 'https://api.github.com/users/redserlabs/repos',
  'events_url': 'https://api.github.com/users/redserlabs/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/redserlabs/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False},
 'html_url': 'https://github.com/redserlabs/python-data-toolbox',
 'description': 'Python practice for data work: scripts, pandas notebooks, and mini projects.',
 'fork': False,
 'url': 'https://api.github.com/repos/redserlabs/python-data-toolbox',
 'forks_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/forks',
 'keys_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/keys{/key_id}',
 'collaborators_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/collaborators{/collaborator}',
 'teams_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/teams',
 'hooks_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/hooks',
 'issue_events_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/issues/events{/number}',
 'events_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/events',
 'assignees_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/assignees{/user}',
 'branches_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/branches{/branch}',
 'tags_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/tags',
 'blobs_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/git/blobs{/sha}',
 'git_tags_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/git/tags{/sha}',
 'git_refs_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/git/refs{/sha}',
 'trees_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/git/trees{/sha}',
 'statuses_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/statuses/{sha}',
 'languages_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/languages',
 'stargazers_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/stargazers',
 'contributors_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/contributors',
 'subscribers_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/subscribers',
 'subscription_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/subscription',
 'commits_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/commits{/sha}',
 'git_commits_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/git/commits{/sha}',
 'comments_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/comments{/number}',
 'issue_comment_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/issues/comments{/number}',
 'contents_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/contents/{+path}',
 'compare_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/compare/{base}...{head}',
 'merges_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/merges',
 'archive_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/{archive_format}{/ref}',
 'downloads_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/downloads',
 'issues_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/issues{/number}',
 'pulls_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/pulls{/number}',
 'milestones_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/milestones{/number}',
 'notifications_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/notifications{?since,all,participating}',
 'labels_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/labels{/name}',
 'releases_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/releases{/id}',
 'deployments_url': 'https://api.github.com/repos/redserlabs/python-data-toolbox/deployments',
 'created_at': '2026-03-24T22:19:53Z',
 'updated_at': '2026-03-26T16:53:36Z',
 'pushed_at': '2026-03-26T16:53:32Z',
 'git_url': 'git://github.com/redserlabs/python-data-toolbox.git',
 'ssh_url': 'git@github.com:redserlabs/python-data-toolbox.git',
 'clone_url': 'https://github.com/redserlabs/python-data-toolbox.git',
 'svn_url': 'https://github.com/redserlabs/python-data-toolbox',
 'homepage': None,
 'size': 38,
 'stargazers_count': 0,
 'watchers_count': 0,
 'language': 'Python',
 'has_issues': True,
 'has_projects': True,
 'has_downloads': True,
 'has_wiki': True,
 'has_pages': False,
 'has_discussions': False,
 'forks_count': 0,
 'mirror_url': None,
 'archived': False,
 'disabled': False,
 'open_issues_count': 0,
 'license': None,
 'allow_forking': True,
 'is_template': False,
 'web_commit_signoff_required': False,
 'has_pull_requests': True,
 'pull_request_creation_policy': 'all',
 'topics': [],
 'visibility': 'public',
 'forks': 0,
 'open_issues': 0,
 'watchers': 0,
 'default_branch': 'main'}

In [5]:
repo_df = pd.DataFrame(repo_data)
repo_df.head()

,id,node_id,name,full_name,private,owner,html_url,description,fork,url,...,is_template,web_commit_signoff_required,has_pull_requests,pull_request_creation_policy,topics,visibility,forks,open_issues,watchers,default_branch
0,1191068241,R_kgDORv5CUQ,python-data-toolbox,redserlabs/python-data-toolbox,False,"{'login': 'redserlabs', 'id': 217943364, 'node...",https://github.com/redserlabs/python-data-toolbox,"Python practice for data work: scripts, pandas...",False,https://api.github.com/repos/redserlabs/python...,...,False,False,True,all,[],public,0,0,0,main
1,1173947055,R_kgDORfkCrw,sql-playbook,redserlabs/sql-playbook,False,"{'login': 'redserlabs', 'id': 217943364, 'node...",https://github.com/redserlabs/sql-playbook,SQL interview prep: DataLemur + LeetCode + bus...,False,https://api.github.com/repos/redserlabs/sql-pl...,...,False,False,True,all,[],public,0,0,0,main

In [6]:
repo_df.shape

(2, 81)

In [7]:
repo_df.columns.tolist()

['id',
 'node_id',
 'name',
 'full_name',
 'private',
 'owner',
 'html_url',
 'description',
 'fork',
 'url',
 'forks_url',
 'keys_url',
 'collaborators_url',
 'teams_url',
 'hooks_url',
 'issue_events_url',
 'events_url',
 'assignees_url',
 'branches_url',
 'tags_url',
 'blobs_url',
 'git_tags_url',
 'git_refs_url',
 'trees_url',
 'statuses_url',
 'languages_url',
 'stargazers_url',
 'contributors_url',
 'subscribers_url',
 'subscription_url',
 'commits_url',
 'git_commits_url',
 'comments_url',
 'issue_comment_url',
 'contents_url',
 'compare_url',
 'merges_url',
 'archive_url',
 'downloads_url',
 'issues_url',
 'pulls_url',
 'milestones_url',
 'notifications_url',
 'labels_url',
 'releases_url',
 'deployments_url',
 'created_at',
 'updated_at',
 'pushed_at',
 'git_url',
 'ssh_url',
 'clone_url',
 'svn_url',
 'homepage',
 'size',
 'stargazers_count',
 'watchers_count',
 'language',
 'has_issues',
 'has_projects',
 'has_downloads',
 'has_wiki',
 'has_pages',
 'has_discussions',
 'forks_count',
 'mirror_url',
 'archived',
 'disabled',
 'open_issues_count',
 'license',
 'allow_forking',
 'is_template',
 'web_commit_signoff_required',
 'has_pull_requests',
 'pull_request_creation_policy',
 'topics',
 'visibility',
 'forks',
 'open_issues',
 'watchers',
 'default_branch']

In [8]:
selected_repo_df = repo_df[
    [
        "id",
        "name",
        "full_name",
        "private",
        "html_url",
        "description",
        "created_at",
        "updated_at",
        "pushed_at",
        "language",
        "visibility"
    ]
]

selected_repo_df.head()

,id,name,full_name,private,html_url,description,created_at,updated_at,pushed_at,language,visibility
0,1191068241,python-data-toolbox,redserlabs/python-data-toolbox,False,https://github.com/redserlabs/python-data-toolbox,"Python practice for data work: scripts, pandas...",2026-03-24T22:19:53Z,2026-03-26T16:53:36Z,2026-03-26T16:53:32Z,Python,public
1,1173947055,sql-playbook,redserlabs/sql-playbook,False,https://github.com/redserlabs/sql-playbook,SQL interview prep: DataLemur + LeetCode + bus...,2026-03-05T23:08:40Z,2026-03-24T21:38:41Z,2026-03-24T21:38:37Z,NaN,public

In [9]:
selected_repo_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           2 non-null      int64
 1   name         2 non-null      str
 2   full_name    2 non-null      str
 3   private      2 non-null      bool
 4   html_url     2 non-null      str
 5   description  2 non-null      str
 6   created_at   2 non-null      str
 7   updated_at   2 non-null      str
 8   pushed_at    2 non-null      str
 9   language     1 non-null      str
 10  visibility   2 non-null      str
dtypes: bool(1), int64(1), str(9)
memory usage: 294.0 bytes

In [10]:
selected_repo_df["created_at"] = pd.to_datetime(selected_repo_df["created_at"])
selected_repo_df["updated_at"] = pd.to_datetime(selected_repo_df["updated_at"])
selected_repo_df["pushed_at"] = pd.to_datetime(selected_repo_df["pushed_at"])

selected_repo_df.dtypes

id                           int64
name                           str
full_name                      str
private                       bool
html_url                       str
description                    str
created_at     datetime64[us, UTC]
updated_at     datetime64[us, UTC]
pushed_at      datetime64[us, UTC]
language                       str
visibility                     str
dtype: object