In [1]:
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "cleaned" / "github_issue_records.csv"

issues_df = pd.read_csv(input_file)
issues_df.head()

,issue_id,issue_number,title,state,created_at,updated_at,user_login,comments
0,4218684145,308230,WAY too many requests to allow something obvious,open,2026-04-07 15:15:37+00:00,2026-04-07 15:15:37+00:00,MarcSchluperAtIntel,0
1,4218680755,308229,Window keeps freezing,open,2026-04-07 15:15:03+00:00,2026-04-07 15:15:03+00:00,jhaase1,0
2,4218674628,308228,missing package-lock changes,open,2026-04-07 15:13:57+00:00,2026-04-07 15:17:14+00:00,joaomoreno,1
3,4218617116,308227,?,open,2026-04-07 15:04:31+00:00,2026-04-07 15:04:31+00:00,AmrGharibx,0
4,4218579314,308226,"i have a problem with my chat on code space, i...",open,2026-04-07 14:58:01+00:00,2026-04-07 14:58:34+00:00,briceT2f,1

In [3]:
issues_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   issue_id      30 non-null     int64
 1   issue_number  30 non-null     int64
 2   title         30 non-null     str
 3   state         30 non-null     str
 4   created_at    30 non-null     str
 5   updated_at    30 non-null     str
 6   user_login    30 non-null     str
 7   comments      30 non-null     int64
dtypes: int64(3), str(5)
memory usage: 2.0 KB

In [4]:
issues_df["created_at"] = pd.to_datetime(issues_df["created_at"])
issues_df["updated_at"] = pd.to_datetime(issues_df["updated_at"])

issues_df.dtypes

issue_id                      int64
issue_number                  int64
title                           str
state                           str
created_at      datetime64[us, UTC]
updated_at      datetime64[us, UTC]
user_login                      str
comments                      int64
dtype: object

In [5]:
issues_df["created_date"] = issues_df["created_at"].dt.date
issues_df["created_hour"] = issues_df["created_at"].dt.hour
issues_df["updated_date"] = issues_df["updated_at"].dt.date
issues_df["update_delay_hours"] = (
    (issues_df["updated_at"] - issues_df["created_at"]).dt.total_seconds() / 3600
)

issues_df.head()

,issue_id,issue_number,title,state,created_at,updated_at,user_login,comments,created_date,created_hour,updated_date,update_delay_hours
0,4218684145,308230,WAY too many requests to allow something obvious,open,2026-04-07 15:15:37+00:00,2026-04-07 15:15:37+00:00,MarcSchluperAtIntel,0,2026-04-07,15,2026-04-07,0.000000
1,4218680755,308229,Window keeps freezing,open,2026-04-07 15:15:03+00:00,2026-04-07 15:15:03+00:00,jhaase1,0,2026-04-07,15,2026-04-07,0.000000
2,4218674628,308228,missing package-lock changes,open,2026-04-07 15:13:57+00:00,2026-04-07 15:17:14+00:00,joaomoreno,1,2026-04-07,15,2026-04-07,0.054722
3,4218617116,308227,?,open,2026-04-07 15:04:31+00:00,2026-04-07 15:04:31+00:00,AmrGharibx,0,2026-04-07,15,2026-04-07,0.000000
4,4218579314,308226,"i have a problem with my chat on code space, i...",open,2026-04-07 14:58:01+00:00,2026-04-07 14:58:34+00:00,briceT2f,1,2026-04-07,14,2026-04-07,0.009167

In [6]:
issues_by_day_df = (
    issues_df.groupby("created_date", as_index=False)["issue_id"]
    .count()
    .rename(columns={"issue_id": "issue_count"})
    .sort_values(by="created_date")
)

issues_by_day_df

  created_date  issue_count
0   2026-04-07           30

In [7]:
issues_by_hour_df = (
    issues_df.groupby("created_hour", as_index=False)["issue_id"]
    .count()
    .rename(columns={"issue_id": "issue_count"})
    .sort_values(by="created_hour")
)

issues_by_hour_df

   created_hour  issue_count
0            11            2
1            12            9
2            13            9
3            14            6
4            15            4

In [8]:
top_users_df = (
    issues_df.groupby("user_login", as_index=False)["issue_id"]
    .count()
    .rename(columns={"issue_id": "issue_count"})
    .sort_values(by="issue_count", ascending=False)
)

top_users_df.head(10)

                  user_login  issue_count
14                   jrieken            2
22                  sandy081            2
21                samvardani            2
0                 AmrGharibx            1
25                     vhxma            1
24               simatao-cpu            1
23                  satyboii            1
20                ryanrocket            1
19  rutvikcodingdolar246-ops            1
18                rohodragon            1

In [9]:
most_commented_issues_df = issues_df.sort_values(by="comments", ascending=False)
most_commented_issues_df.head(10)

,issue_id,issue_number,title,state,created_at,updated_at,user_login,comments,created_date,created_hour,updated_date,update_delay_hours
15,4217955027,308211,add logging,open,2026-04-07 13:22:43+00:00,2026-04-07 13:25:48+00:00,sandy081,1,2026-04-07,13,2026-04-07,0.051389
17,4217840212,308207,update.titleBar setting no longer recognized a...,open,2026-04-07 13:02:30+00:00,2026-04-07 13:42:49+00:00,Kvan7,1,2026-04-07,13,2026-04-07,0.671944
2,4218674628,308228,missing package-lock changes,open,2026-04-07 15:13:57+00:00,2026-04-07 15:17:14+00:00,joaomoreno,1,2026-04-07,15,2026-04-07,0.054722
4,4218579314,308226,"i have a problem with my chat on code space, i...",open,2026-04-07 14:58:01+00:00,2026-04-07 14:58:34+00:00,briceT2f,1,2026-04-07,14,2026-04-07,0.009167
25,4217606586,308199,GitHub Copilot Broken this Morning,open,2026-04-07 12:21:54+00:00,2026-04-07 12:48:29+00:00,qwtm,1,2026-04-07,12,2026-04-07,0.443056
8,4218195351,308219,hanging on fetching PDF url that saved to down...,open,2026-04-07 14:01:32+00:00,2026-04-07 14:45:45+00:00,ryanrocket,1,2026-04-07,14,2026-04-07,0.736944
24,4217634758,308200,Chat is unresponsive,open,2026-04-07 12:27:18+00:00,2026-04-07 12:40:39+00:00,GloryFlory,1,2026-04-07,12,2026-04-07,0.222500
28,4217418517,308194,Broken serialization,open,2026-04-07 11:44:54+00:00,2026-04-07 12:40:51+00:00,rohodragon,0,2026-04-07,11,2026-04-07,0.932500
27,4217508641,308196,sunm,open,2026-04-07 12:02:17+00:00,2026-04-07 12:40:48+00:00,eriperdana598-netizen,0,2026-04-07,12,2026-04-07,0.641944
26,4217568796,308198,Feature Request: Add a setting to configure th...,open,2026-04-07 12:14:24+00:00,2026-04-07 12:45:12+00:00,markusfalk,0,2026-04-07,12,2026-04-07,0.513333

In [10]:
issues_df[["comments", "update_delay_hours"]].describe()

        comments  update_delay_hours
count  30.000000           30.000000
mean    0.233333            0.471407
std     0.430183            0.414327
min     0.000000            0.000000
25%     0.000000            0.024097
50%     0.000000            0.436528
75%     0.000000            0.755486
max     1.000000            1.247500

In [11]:
issues_df[[
    "issue_number",
    "title",
    "created_at",
    "updated_at",
    "created_hour",
    "comments",
    "update_delay_hours"
]].head(10)

,issue_number,title,created_at,updated_at,created_hour,comments,update_delay_hours
0,308230,WAY too many requests to allow something obvious,2026-04-07 15:15:37+00:00,2026-04-07 15:15:37+00:00,15,0,0.000000
1,308229,Window keeps freezing,2026-04-07 15:15:03+00:00,2026-04-07 15:15:03+00:00,15,0,0.000000
2,308228,missing package-lock changes,2026-04-07 15:13:57+00:00,2026-04-07 15:17:14+00:00,15,1,0.054722
3,308227,?,2026-04-07 15:04:31+00:00,2026-04-07 15:04:31+00:00,15,0,0.000000
4,308226,"i have a problem with my chat on code space, i...",2026-04-07 14:58:01+00:00,2026-04-07 14:58:34+00:00,14,1,0.009167
5,308225,Claude not usable anymore,2026-04-07 14:47:19+00:00,2026-04-07 14:47:19+00:00,14,0,0.000000
6,308223,Makes fixtures more stable,2026-04-07 14:26:42+00:00,2026-04-07 15:09:26+00:00,14,0,0.712222
7,308221,Manual GPT-5.4 selection falls back to another...,2026-04-07 14:19:55+00:00,2026-04-07 14:45:43+00:00,14,0,0.430000
8,308219,hanging on fetching PDF url that saved to down...,2026-04-07 14:01:32+00:00,2026-04-07 14:45:45+00:00,14,1,0.736944
9,308218,fucking annoying you idiots,2026-04-07 14:00:20+00:00,2026-04-07 14:45:47+00:00,14,0,0.757500