In [1]:
import pandas as pd
from pathlib import Path

In [2]:
project_root = Path.cwd().parent.parent
input_file = project_root / "data" / "cleaned" / "retail" / "online_retail_clean.csv"

df = pd.read_csv(input_file)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

In [3]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["InvoiceMonth"] = df["InvoiceDate"].dt.to_period("M").astype(str)

In [4]:
monthly_revenue_df = (
    df.groupby("InvoiceMonth", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="InvoiceMonth")
)

monthly_revenue_df.head()

  InvoiceMonth     Revenue
0      2010-12  572713.890
1      2011-01  569445.040
2      2011-02  447137.350
3      2011-03  595500.760
4      2011-04  469200.361

In [5]:
country_revenue_df = (
    df.groupby("Country", as_index=False)["Revenue"]
    .sum()
    .sort_values(by="Revenue", ascending=False)
)

country_revenue_df.head(10)

           Country      Revenue
35  United Kingdom  7308391.554
23     Netherlands   285446.340
10            EIRE   265545.900
14         Germany   228867.140
13          France   209024.050
0        Australia   138521.310
30           Spain    61577.110
32     Switzerland    56443.950
3          Belgium    41196.340
31          Sweden    38378.330

In [6]:
export_dir = project_root / "data" / "exports" / "retail"
export_dir.mkdir(parents=True, exist_ok=True)

monthly_revenue_file = export_dir / "monthly_revenue.csv"
country_revenue_file = export_dir / "country_revenue.csv"

In [7]:
monthly_revenue_df.to_csv(monthly_revenue_file, index=False)
country_revenue_df.to_csv(country_revenue_file, index=False)

print(f"File saved: {monthly_revenue_file}")
print(f"File saved: {country_revenue_file}")

File saved: /Users/reda.serhir/Documents/Projects/Github/python-data-toolbox/data/exports/retail/monthly_revenue.csv
File saved: /Users/reda.serhir/Documents/Projects/Github/python-data-toolbox/data/exports/retail/country_revenue.csv

In [8]:
monthly_revenue_check = pd.read_csv(monthly_revenue_file)
country_revenue_check = pd.read_csv(country_revenue_file)

monthly_revenue_check.head()

  InvoiceMonth     Revenue
0      2010-12  572713.890
1      2011-01  569445.040
2      2011-02  447137.350
3      2011-03  595500.760
4      2011-04  469200.361

In [9]:
country_revenue_check.head(10)

          Country      Revenue
0  United Kingdom  7308391.554
1     Netherlands   285446.340
2            EIRE   265545.900
3         Germany   228867.140
4          France   209024.050
5       Australia   138521.310
6           Spain    61577.110
7     Switzerland    56443.950
8         Belgium    41196.340
9          Sweden    38378.330